/*
 * SPDX-License-Identifier: MIT
 *
 * Zephyr Edge AI Demo - Gesture Recognition Model Data
 *
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT
 * Generated by: model/train_gesture_model.py
 *
 * Model: Gesture classification (IDLE, WAVE, TAP, CIRCLE)
 * Input: 150 INT8 values (50 samples x 3 axes, flattened)
 * Output: 4 class probabilities (INT8)
 * Architecture: Dense(32) -> Dense(16) -> Dense(4)
 * Size: 8040 bytes
 */

#ifndef GESTURE_MODEL_H
#define GESTURE_MODEL_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Model data array */
extern const unsigned char gesture_model_data[];

/* Model size in bytes */
extern const size_t gesture_model_data_len;

#ifdef __cplusplus
}
#endif

#endif /* GESTURE_MODEL_H */
